export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_RESULT = 'FETCH_USERS_RESULT';
export const FETCH_MESSAGE_THREADS_START = 'FETCH_MESSAGE_THREADS_START';
export const FETCH_MESSAGE_THREADS_RESULT = 'FETCH_MESSAGE_THREADS_RESULT';
export const FETCH_MESSAGE_THREAD_START = 'FETCH_MESSAGE_THREAD_START';
export const FETCH_MESSAGE_THREAD_RESULT = 'FETCH_MESSAGE_THREAD_RESULT';
export const SET_ACTIVE_MESSAGE_THREAD = 'SET_ACTIVE_MESSAGE_THREAD';
